name: Build and deploy a container to an Azure Web App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.100
      - name: Restore dependences
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish mwo4.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: Create version
        run: |
              echo ${{ github.run_number }} > ${{ env.DOTNET_ROOT }}/api/version.txt
      - name: upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mwo-artifact
          path: ${{ env.DOTNET_ROOT }}/api
    
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: mwo-artifact
      - name: Azure WebApp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'DEVmwo'
          publish-profile: ${{ secrets.DEV_MWO }}
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'PROD'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: mwo-artifact
      - name: Azure WebApp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'PRODmwo'
          publish-profile: ${{ secrets.PROD_MWO }}
            
